name: Build SDK

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Install PowerShell
    - name: Install PowerShell
      run: |
        # Update the list of products
        sudo apt-get update
        # Install a basic PowerShell environment
        sudo apt-get install -y powershell

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    # Run build script
    - name: Build-RscSdk.ps1
      run: pwsh -File Utils/Build-RscSdk.ps1
